### ISSUE TITLE
Not able to copy all of chat into clipboard

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#14]
I tried to copy all of chat to the clipboard on Windows so that I could paste it in my private OneNote in order to keep a record of it.  I clicked in the chat window and pressed Ctrl+A, which seemingly selected everything, and then Ctrl+C to copy to the clipboard.  When I pasted in OneNote, however, only a small fraction of the chat messages were pasted.  It appears the only messages that make it into the clipboard are the ones that are visible at the moment I copy to the clipboard.

**To Reproduce**

1. Go into any channel.
2. Wait until enough chat messages have been received that they span many "pages" (many times the visible vertical height of the window).
3. Click anywhere in the chat log.
4. Press Ctrl+A.
5. Press Ctrl+C.
6. Click into any text editor and press Ctrl+V.

**Expected behavior**

I expected the text of all chat messages collected to be pasted.

**Screenshots**

I'm guessing screenshots wouldn't add any helpful information here.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.7.0
| Browser          | Firefox 63.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
# The issue

So what's really happening here when you're pressing `Ctrl + A` & `Ctrl + C` is that you're copying from the DOM directly but as you've realised, only a small portion of the messages are actually in the DOM.

This is not a *"bug"* per-se as this is part of a set of explicit optimisations I made as having everything in the DOM would be pretty bad performance-wise, specially in large & fast chats.

Here is some admArt which I think will be better than words kinda simplifying and trying to explain what's really happening with messages in YaTA:

![DOM](https://i.imgur.com/LCRBVcv.png)

As you can see, only a very small portion of the messages is actually in the DOM and as chat is moving and you are scrolling, we're performing various mutations so that only some messages are in the DOM (with a buffer so that you don't see it even if scrolling very fast) in order to show you what you expect to see and in the fastest way possible.

# The solution

As I'm obviously not remove all these optimisations, and as the copy you intended to make was in order to save logs in a private notebook, the solution I choose was to make available logs exportable through a proper UI and of course, it'll export everything and not only what's *visible*.

![Preview](https://i.imgur.com/U0dA6k9.png)

You can pick exactly what you want to export, copy to your clipboard, save to a file, etc…

I hope this solution will fit your needs (if not, do not hesitate to comment, re-open, etc…)

*Note: this will only be available in the next version (no ETA yet).*
