### ISSUE TITLE
Option for chat reversed order

### ISSUE THREAD

**Issue by tollus** [HiDeoo/YaTA#25]
**Is your feature request related to a problem? Please describe.**

When I stream I would rather look at the top of my screen vs the bottom of the screen to see the latest messages. I attempted to do this myself, but I can't figure out where to make the changes.

**Describe the solution you'd like**

If we can get a setting somewhere to reverse the chat so the latest messages are at the top of the screen, and you scroll down to see old chat, that would be awesome for me.

**Describe alternatives you've considered**

I attempted to modify the code, but couldn't figure it out. I had originally assumed it would be pretty simple, but it was past my beginner React knowledge.

**Additional context**

Thanks! (I should also mention, if you want to just point me to the right direction for modifying the List component, I can try to make the changes)

**Comment by HiDeoo** [comment]
This feature is not something I'm ready to tackle right now (not scratching it at all from my list tho) due to the time I can put in YaTA right now and the time this change would involve as when you get the list rendered in the other direction, there would still be lots of adjustments to make it look good & polished:

- Adjust all the automatic scrolling behavior to take this option into consideration.
- Adjust the pause feature to take this option into consideration.
- Make sure every places showing messages use this option like the chat log for a specific user, etc.
- Make sure the order is respected when copying multiple chat messages, exporting logs, etc.

On the other end, I did some researchs / experiments in case you would want to have a basic / rough version for you locally or even setup a complete PR and get you started. You're mentionning `List` and I think you're referring to the `react-virtualized` component but I don't think it's the correct approach.

I think modifying the `getLogs()` [Redux selector](https://github.com/reduxjs/reselect) (`src/store/selectors/logs.ts`) would be a better choice. You could compose it with another selector or take a parameter for the order (first option sounds like the better one) and just simply change the logs order. For example, for a very basic approach, just chaining `.reverse()` to the logs `_.map` already produce what you want:

![reverse](https://user-images.githubusercontent.com/494699/57688987-f57a6580-763e-11e9-80d6-130bd8b03508.gif)

For a more robust approach, I think using `_.reduceRight` instead of chaining a `.reverse()` after the `_.map` might be better to avoid the extra overhead.

If you have any more question regarding this or if you end up trying that yourself and hit an issue, do not hesitate to comment in this issue, I'll be happy to help.

**Comment by tollus** [comment]
Great, thanks @HiDeoo I'll give that a shot. No worries at all regarding not being able to do it now.

**Comment by tollus** [comment]
I got it to work with the changes you suggested, but you're right, it definitely messes up the scrolling. I was able to prevent the auto scrolling, but it would definitely require some logic to handle the 'pause scrolling' and other stuff.

After using it for a stream, I don't think I'm going to continue with it, it confused me too much I think. 😂

**Comment by HiDeoo** [comment]
Ho boy, you managed to last for 1 entire stream, I gave up with my very basic approach after like 5mn, I was so confused 😂
