### ISSUE TITLE
Display "highlighted messages" specially

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#30]
**Is your feature request related to a problem? Please describe.**

There is a new Twitch feature called [Channel Points](https://help.twitch.tv/s/article/channel-points-guide) and it's enabled for some streams.  One of them happens to be [TimBeaudet](https://www.twitch.tv/timbeaudet).  I noticed one of the things you can do with "channel points" is redeem some to highlight one of your messages.  I tried it out and saw that an extra tag of `msg-id=highlighted-message` is present in the raw message, and in Twitch chat it shows an extra bar on the side (not sure what other people see though).  However, on YaTA there is no special highlight for the message.

**Describe the solution you'd like**

I think if a message is marked as a highlighted message, YaTA should highlight it in some way similar to how Twitch intended.

**Describe alternatives you've considered**

Obviously the alternative would be to use the built-in Twitch chat to see the highlighted messages.

**Additional context**

Here's what a "highlighted message" looks like in both built-in Twitch chat (left) and in YaTA (right).

![image](https://user-images.githubusercontent.com/41497796/65088328-ca49af00-d96d-11e9-9a99-2bf189f81698.png)

Here is another example I captured earlier, showing a raw message marked as a "highlighted message":

```
@badge-info=subscriber/7;badges=subscriber/6;color=#FF0000;display-name=rhymu8354;emotes=;flags=;id=c1c836ac-9075-4a7c-b4f2-bf9bf5ff5f3f;mod=0;msg-id=highlighted-message;room-id=30693918;subscriber=1;tmi-sent-ts=1568763492950;turbo=0;user-id=62966477;user-type= :rhymu8354!rhymu8354@rhymu8354.tmi.twitch.tv PRIVMSG #timbeaudet :What does "highlight my message" do?
```

**Comment by HiDeoo** [comment]
Thanks for the detailed issue 😄 

I added a todo in my notes regarding this feature the day it was announced and since then checked some channels that enabled this new feature, and I have to say, I still haven't a strong opinion on how to handle this kind of messages, specially as 90% is kinda useless spam / people checking the new feature / not really doing what I personally would expect so far.

The various options I've considered:

1. Ignoring it
2. Ignoring it by default and have a setting (false by default) to highlight it
3. Highlighting it by default and have a setting to ignore them
4. Highlighting it

Option 2 or 1 are so far what I think makes more sense to me but I'll continue checking a bit some channels using the feature to see how it's used / maybe ask some users as I won't be able to tackle this until end of next week anyway ^^

**Comment by rhymu8354** [comment]
No problem, I just noticed it wasn't in YaTA and didn't know if you were aware of it or not.  I think ignoring it always or by default is fine.

**Comment by HiDeoo** [comment]
Messages redeemed using Channel Points will now be *slightly* highlighted in the next version.

I went with a way less "flashy" highlight compared to Twitch:

<img width="353" alt="Screenshot 2019-10-02 at 13 39 35" src="https://user-images.githubusercontent.com/494699/66042088-d1e78700-e51b-11e9-99eb-f036054e46d2.png">

It's not that visible and I don't show the number of points used (which is always the same anyway for a message) and the icon.

<img width="747" alt="Screenshot 2019-10-02 at 13 35 10" src="https://user-images.githubusercontent.com/494699/66042125-eaf03800-e51b-11e9-8f0b-e804a47d2c03.png">

We'll see how this feature evolves with time and if it needs adjustments.
