### ISSUE TITLE
Emote rendering over next message

### ISSUE THREAD

**Issue by ghost** [HiDeoo/YaTA#4]
**Describe the bug**

I found whenever I write a message ending with an emote and the emote is the only thing which will be placed on a new line, the height of the message is just text before the emote. Also the emote itself is cut off. See screenshots.
Also the emote is on top of the message of the next person in chat.

| key | value
|----|----
|Width| 568 pixels
|Height| 1079 pixels
|Zoom level| 150%
|Browser| Firefox Quantum version 61.0.1 (64-bit)

**To Reproduce**

1. Set browser zoom to 150%
2. Join a chat
3. Write a message ending with an emote.
3.1. Make sure the emote should be placed a new line.

**Expected behavior**
A message spread over two lines.
The message is on the first line and the second line just contains the emote.

**Screenshots**

Image where my message is the last message in chat
[Image one](https://i.imgur.com/ThSdTrS.png)

Whenever someone (else) writes another message in chat.
[Image two](https://i.imgur.com/RaFF2eW.png)

Image of the full chat session / window
[Image three](https://i.imgur.com/jbcARP8.png)
My message is in the middle of the chat

[Image four](https://i.imgur.com/32amwbE.png) _Added via edit_
In this image I have Chrome on the left and Firefox on the right.
Both have the same zoom level and about the same width.
As you can see in Firefox my message (second to last message) is not formatted properly.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.0.0
| Browser          | Firefox 61.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Thanks for the super detailed issue 👍 

This seems to be related to a pretty old [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1149357) which is fixed in the next version (62).

I made a comparison between Chrome, FF 61 & FF 62 when using a 150% zoom level and we can clearly see extra margins around the image in FF 61.

<img width="429" alt="bug" src="https://user-images.githubusercontent.com/494699/43838727-7563ece8-9b1c-11e8-829e-0e5ae33b9706.png">
