### ISSUE TITLE
Sometimes difficult to read action (/me) message which tags the user

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#44]
**Describe the bug**

If another user sends an "action" (message starting with "/me") that tags me, it's difficult to see the tag if the foreground and background colors are very similar.  See screen-shot.

**To Reproduce**

Have someone set their name color to red and then send a message beginning with "/me" that includes your user name.

**Expected behavior**

I would expect the foreground color inside the tag to be white, rather than red, so it has contrast vs. the red tag background.

**Screenshots**

![image](https://user-images.githubusercontent.com/41497796/77487510-de280f00-6def-11ea-8d32-4c35e6170a67.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.13.3
| Browser          | Firefox 74.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Thanks for the detailed report as usual. This will be fixed in the next version.

Before:

<img width="91" alt="Screenshot 2020-05-05 at 13 52 18" src="https://user-images.githubusercontent.com/494699/81064172-80501200-8ed9-11ea-8881-f0ad9d1c5c32.png">

After:

<img width="90" alt="Screenshot 2020-05-05 at 13 55 51" src="https://user-images.githubusercontent.com/494699/81064178-834b0280-8ed9-11ea-9d92-e972d7e6c16b.png">
